#!/bin/bash
### BEGIN INIT INFO
# Provides: monitortizar_logs_sysv
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: monitoritzar logs del SysV
# Description:
### END INIT INFO

PATH=/bin:/sbin:/usr/bin:/usr/sbin
SERVICE_SCRIPT="/usr/local/bin/monitoritzar_logs.sh"
PIDFILE="/var/run/monitoritzar_logs.pid"

SERVICE_NAME="monitoritzar_logs"
LOG_FILE="/var/log/$SERVICE_NAME.log"

case "$1" in
    start)
        echo "Iniciant $SERVICE_NAME..." | tee -a "$LOG_FILE"
        ./${SERVICE_SCRIPT} "-u cron -u rsyslog -u redys" 1> "$LOG_FILE" &
        ;;
    stop)
        echo "Aturant $SERVICE_NAME..." | tee -a "$LOG_FILE"
        ;;
    restart)
        echo "Reiniciant $SERVICE_NAME..." | tee -a "$LOG_FILE"
        ;;
    status)
        echo "Comprovant l'estat de $SERVICE_NAME..." | tee -a "$LOG_FILE"
        ;;
    custom)
        echo "Executant acció personalitzada amb paràmetres: $2 $3..." | tee -a "$LOG_FILE"
        # Exemple de com processar altres paràmetres
        if [[ -n "$2" ]]; then
        echo "Paràmetre 1: $2" | tee -a "$LOG_FILE"
        fi
        if [[ -n "$3" ]]; then
        echo "Paràmetre 2: $3" | tee -a "$LOG_FILE"
        fi
        ;;
    *)
        echo "Ús: $0 {start|stop|restart|status|custom <args>}" | tee -a "$LOG_FILE"
        exit 1
        ;;
esac

exit 0
